<#
Comming up:

- Download Windows
    - Language
- Create Autounattend
    - Language (From Windows selection)
    - Debloat
    - Security settings
    - Download/Install Chrome, Adobe Acrobat, 7zip
    - Download/Install Office 365 / 2016 Pro
- Deploy Autounattend
    - DISM
- Install ventoy
    - Ventoy config
    - Ventoy icons


/UltimateUSB.PS1
    /res/Autounatted-example.xml
    /res/languages-keyboard.txt
    /res/languages-system.txt
    /res/Ventoy-config.txt
    /res/Icons/...
    /res/Modules/...

#>